### PR TITLE
pom.xml: bump build-tools and fix rpmlint error

### PR DESCRIPTION
**Pull request by stdweird**
Bump buildtools to 1.49 to fix rpmlint `no-changelogname-tag` error

### CODE REVIEW

**Comment by stdweird** [comment]
before
```
perl-LC.noarch: W: non-standard-group Quattor
perl-LC.noarch: E: no-changelogname-tag
perl-LC.noarch: W: invalid-license Quattor
```
after
```
perl-LC.noarch: W: non-standard-group Quattor
```

**Comment by jrha** [comment]
The description box at the top of the page is ideally that's where your comments about each PR should be, rather than in a follow up comment.
You can always edit the initial text...

**Comment by jrha** [comment]
We should probably consider changing the group to `Applications/System`, it seems to be the best fit out of the standard groups.

**Comment by stdweird** [comment]
@jrha open an issue in `maven-tools` for that. wrt to the descrition box, i always tought that it ends up in the release notes. not sure you want this data in there.

**Comment by jouvin** [comment]
I think that only the title ends up in the release notes, isn't it?

**Comment by jrha** [comment]
@jouvin correct

**Comment by jrha** [comment]
@stdweird, I don't really mind, but it would be good to have *something* in the box.

**Comment by stdweird** [comment]
@jrha sufficient

**Comment by jrha** [comment]
Beautiful.

**Pull request merged**
